# server.port: 8081
# debug: true

initializr:
  description:
    value: Demo project using start.xenit.eu
  types:
  - name: Alfred Gradle SDK
    id: gradle-project
    description: Generate a Gradle based module archive
    tags:
      build: gradle
      format: module
    default: true
    action: /starter.zip
  - name: Gradle Config
    id: gradle-build
    description: Generate a Gradle build file
    tags:
      build: gradle
      format: build
    default: false
    action: /build.gradle
  - name: Alfresco Maven SDK
    id: maven-project
    description: Generate a Maven based module archive
    tags:
      build: maven
      format: module
    default: false
    action: /starter.zip
  bootVersions:
  - name: Enterprise 5.2.5
    id: 5.2.5
    default: true
  javaVersions:
  - id: 1.8
    default: true
  - id: 1.7
  languages:
  - name: Java
    id: java
    default: true
  packagings:
  - name: Amp
    id: amp
    default: true
  - name: Jar
    id: jar


  dependencies:
  - name: Alfresco Zipkin Repo
    content:
    - name: Alfresco Zipkin Repo
      id: alfresco-zipkin-repo
      facets:
      - zipkin
      - alfresco-zipkin-repo
      groupId: eu.xenit.alfred.edge
      artifactId: alfresco-zipkin-repo
      version: 1.1.1-SNAPSHOT
      description: Zipkin instrumentation for Alfresco Repository

  - name: Alfresco Zipkin Share
    content:
    - name: Alfresco Zipkin Share
      id: alfresco-zipkin-share
      facets:
      - share-war
      - zipkin
      - alfresco-zipkin-share
      groupId: eu.xenit.alfred.edge
      artifactId: alfresco-zipkin-share
      version: 1.1.1-SNAPSHOT
      description: Zipkin instrumentation for Alfresco Share

  - name: Share War
    content:
    - name: Share War
      id: share-war
      facets:
      - share-war
      groupId: org.alfresco
      artifactId: share
      version: 5.2.5
      description: Alfresco share war

  - name: Dynamic Extensions
    content:
    - name: Dynamic Extensions
      id: dynamic-extensions
      facets:
      - platform
      - alfrescoAmp
      groupId: eu.xenit
      artifactId: alfresco-dynamic-extensions-repo
      version: 2.0.1
      description: Rapid development of Alfresco repository extensions.
      mappings:
      - versionRange: "[5.2.0,5.3.0)"
        artifactId: alfresco-dynamic-extensions-repo-52

  - name: Alfred API
    content:
    - name: Alfred API
      facets:
      - dynamic-extensions
      - platform
      id: apix
      groupId: eu.xenit.apix
      artifactId: alfred-api
      version: 2.0.1-RC2
      description: Alfred API allows you to access Alfresco in a standardised way.

  - name: Monitoring
    content:
    - id: alfred-telemetry
      name: Alfred Telemetry
      description: Provides metrics for Alfresco using micrometer.io, a vendor-neutral application metrics facade.
      groupId: eu.xenit.alfred.telemetry
      artifactId: alfred-telemetry-platform
      type: amp
      version: 0.1.0
      weight: 10
      facets:
      - telemetry
    - id: micrometer-graphite
      name: Micrometer Graphite Registry
      description: Export Micrometer metrics to Graphite registry
      groupId: io.micrometer
      artifactId: micrometer-registry-graphite
      version: 1.0.6
      facets:
      - telemetry
      - alfrescoSM
      - grafana